# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pr-checks/sync.sh
# to regenerate this file.

name: PR Check - Autobuild direct tracing
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
      - main
      - releases/v*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      java-version:
        type: string
        description: The version of Java to install
        required: false
        default: '17'
  workflow_call:
    inputs:
      java-version:
        type: string
        description: The version of Java to install
        required: false
        default: '17'
jobs:
  autobuild-direct-tracing:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            version: linked
          - os: windows-latest
            version: linked
          - os: ubuntu-latest
            version: nightly-latest
          - os: windows-latest
            version: nightly-latest
    name: Autobuild direct tracing
    permissions:
      contents: read
      security-events: read
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Prepare test
        id: prepare-test
        uses: ./.github/actions/prepare-test
        with:
          version: ${{ matrix.version }}
          use-all-platform-bundle: 'false'
          setup-kotlin: 'true'
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version || '17' }}
          distribution: temurin
      - name: Set up Java test repo configuration
        shell: bash
        run: |
          mv * .github ../action/tests/multi-language-repo/
          mv ../action/tests/multi-language-repo/.github/workflows .github
          mv ../action/tests/java-repo/* .

      - uses: ./../action/init
        id: init
        with:
          build-mode: autobuild
          db-location: ${{ runner.temp }}/customDbLocation
          languages: java
          tools: ${{ steps.prepare-test.outputs.tools-url }}

      - name: Check that indirect tracing is disabled
        shell: bash
        run: |
          if [[ ! -z "${CODEQL_RUNNER}" ]]; then
            echo "Expected indirect tracing to be disabled, but the" \
              "CODEQL_RUNNER environment variable is set."
            exit 1
          fi

      - uses: ./../action/analyze
    env:
      CODEQL_ACTION_AUTOBUILD_BUILD_MODE_DIRECT_TRACING: true
      CODEQL_ACTION_TEST_MODE: true
