name: Update Supported Enterprise Server Versions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-supported-enterprise-server-versions:
    name: Update Supported Enterprise Server Versions
    timeout-minutes: 45
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'github/codeql-action' }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Checkout CodeQL Action
        uses: actions/checkout@v3
      - name: Checkout Enterprise Releases
        uses: actions/checkout@v3
        with:
          repository: github/enterprise-releases
          ssh-key: ${{ secrets.ENTERPRISE_RELEASES_SSH_KEY }}
          path: ${{ github.workspace }}/enterprise-releases/
      - name: Update Supported Enterprise Server Versions
        run: |
          cd ./.github/workflows/update-supported-enterprise-server-versions/
          python3 -m pip install pipenv
          pipenv install
          pipenv run ./update.py
          rm --recursive "$ENTERPRISE_RELEASES_PATH"
          npm run build
        env:
          ENTERPRISE_RELEASES_PATH: ${{ github.workspace }}/enterprise-releases/
      - name: Commit Changes
        uses: peter-evans/create-pull-request@284f54f989303d2699d373481a0cfa13ad5a6666 # v5.0.1
        with:
          commit-message: Update supported GitHub Enterprise Server versions.
          title: Update supported GitHub Enterprise Server versions.
          body: ""
          author: GitHub <noreply@github.com>
          branch: update-supported-enterprise-server-versions
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
